network:
  version: 2
  ethernets:
    ens160:
      dhcp4: no
      dhcp6: no
      addresses: 
        - 10.1.2.3/24
      routes:
        - to: default
          via: 10.1.2.1
          metric: 100
          on-link: true
      mtu: 1500
      nameservers:
        addresses: [ 10.2.3.4, 10.4.5.6 ]
        search: [ domain.com ]
